# Generated by Django 6.0.2 on 2026-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='citizenship',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='civil_status',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='currently_working',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='monthly_income',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='residency_years',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
