# Generated by Django 6.0.2 on 2026-03-06 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='programs.program')),
            ],
            options={
                'db_table': 'programs_documentrequirement',
                'ordering': ['program', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('submitted', 'Submitted'), ('invalid', 'Invalid')], default='missing', max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='application_docs/%Y/%m/')),
                ('issue_notes', models.CharField(blank=True, max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='programs.application')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='programs.documentrequirement')),
            ],
            options={
                'db_table': 'programs_applicationdocument',
                'unique_together': {('application', 'requirement')},
            },
        ),
    ]
