# Generated by Django 6.0.2 on 2026-03-06 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_documentrequirement_applicationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rule_type', models.CharField(choices=[('eligibility', 'Eligibility'), ('conflict', 'Conflict'), ('completeness', 'Completeness')], max_length=32)),
                ('definition', models.JSONField(blank=True, default=dict, help_text='Rule parameters, e.g. {"check_prior_assistance": true}')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='programs.program')),
            ],
            options={
                'db_table': 'programs_programrule',
                'ordering': ['program', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('flag', 'Flag')], max_length=32)),
                ('reasons', models.JSONField(default=list, help_text='List of rule names or reasons that triggered a Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_result', to='programs.application')),
            ],
            options={
                'db_table': 'programs_screeningresult',
            },
        ),
    ]
