# Generated by Django 6.0.2 on 2026-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_programrule_screeningresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='educational_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
