# Generated by Django 6.0.2 on 2026-04-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_application_educational_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown to applicants on the programs list.'),
        ),
    ]
