# Generated by Django 6.0.2 on 2026-05-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_archive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('for_review', 'In Review'), ('approved', 'Approved'), ('awaiting_physical', 'Approved – Awaiting Physical Submission'), ('rejected', 'Rejected')], default='draft', max_length=32),
        ),
    ]
