# Generated by Django 6.0.2 on 2026-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programrule',
            name='definition',
        ),
        migrations.AddField(
            model_name='programrule',
            name='condition',
            field=models.CharField(blank=True, choices=[('lte', 'Must not exceed'), ('gte', 'Must be at least'), ('equals', 'Must be equal to'), ('not_equals', 'Must not be'), ('in_list', 'Must be one of (comma-separated)'), ('date_after', 'Must be on or after (YYYY-MM-DD)'), ('date_before', 'Must be on or before (YYYY-MM-DD)')], max_length=32),
        ),
        migrations.AddField(
            model_name='programrule',
            name='rule_field',
            field=models.CharField(blank=True, choices=[('monthly_income', 'Monthly Income'), ('residency_years', 'Years of Residency'), ('barangay', 'Barangay'), ('citizenship', 'Citizenship'), ('civil_status', 'Civil Status'), ('currently_working', 'Employment Status'), ('gender', 'Gender'), ('course', 'Course / Degree'), ('school', 'School'), ('graduation_date', 'Graduation Date')], max_length=64),
        ),
        migrations.AddField(
            model_name='programrule',
            name='value',
            field=models.CharField(blank=True, help_text='The value to compare against. For "Must be one of", separate values with commas. For dates, use YYYY-MM-DD format.', max_length=255),
        ),
    ]
