# Generated by Django 6.0.2 on 2026-05-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_update_programrule_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='application_docs/%Y/%m/'),
        ),
    ]
